### ISSUE TITLE
Unraid Docker Timeout error

### ISSUE THREAD

**Issue by ich777** [CatalysmsServerManager/7-days-to-die-server-manager#150]
**Describe the bug**
Some users of my Unraid Docker container for CSMM are reporting that something is timing out when starting the container, I'm not able to reproduce this error on my server.
Since I'm not very familar with Node eventually someone can help and I can fix it in the container itself?

Here is the log output:
[log.log](https://github.com/CatalysmsServerManager/7-days-to-die-server-manager/files/4883363/log.log)

Here is the link to the post on the Unraid forum:
https://forums.unraid.net/topic/79530-support-ich777-gameserver-dockers/?do=findComment&comment=872511

**Comment by niekcandaele** [comment]
```
2020-07-07T03:02:16.597Z - [31merror[39m: HOOKS - sdtdLogs message=Unexpected error from database adapter: ER_NO_SUCH_TABLE: Table '7dtd.sdtdconfig' doesn't exist, name=AdapterError, name=AdapterError, adapterMethodName=find, modelIdentity=sdtdconfig, code=ER_NO_SUCH_TABLE, errno=1146, sqlMessage=Table '7dtd.sdtdconfig' doesn't exist, sqlState=42S02, index=0, sql=select `createdAt`, `updatedAt`, `id`, `inactive`, `inventoryTracking`, `locationTracking`, `economyEnabled`, `currencyName`, `killEarnerEnabled`, `zombieKillReward`, `playerKillReward`, `playtimeEarnerEnabled`, `playtimeEarnerInterval`, `playtimeEarnerAmount`, `discordTextEarnerEnabled`, `discordTextEarnerAmountPerMessage`, `discordTextEarnerTimeout`, `discordTextEarnerIgnoredChannels`, `costToTeleport`, `costToSetTeleport`, `costToMakeTeleportPublic`, `costToUseGimme`, `commandsEnabled`, `commandPrefix`, `enabledCallAdmin`, `enabledPlayerTeleports`, `enabledWho`, `enabledGimme`, `maxPlayerTeleportLocations`, `playerTeleportDelay`, `playerTeleportTimeout`, `gimmeCooldown`, `discordPrefix`, `discordGuildId`, `chatChannelId`, `chatChannelRichMessages`, `chatChannelGlobalOnly`, `chatChannelBlockedPrefixes`, `discordNotificationConfig`, `gblNotificationBans`, `gblAutoBanEnabled`, `gblAutoBanBans`, `loggingEnabled`, `memUpdateInfoEnabled`, `countryBanConfig`, `pingKickEnabled`, `maxPing`, `pingChecksToFail`, `pingKickMessage`, `pingWhitelist`, `votingApiKey`, `votingEnabled`, `votingCommand`, `bannedItemsEnabled`, `bannedItems`, `bannedItemsCommand`, `server` from `sdtdconfig` where `loggingEnabled` = true and `inactive` = false limit 9007199254740991, isOperational=true, stack=AdapterError: Unexpected error from database adapter: ER_NO_SUCH_TABLE: Table '7dtd.sdtdconfig' doesn't exist
at Sails.sails.on (/csmm-7dtd/CSMM/api/hooks/sdtdLogs/index.js:33:49)
at process._tickCallback (internal/process/next_tick.js:68:7), adapterMethodName=find, modelIdentity=sdtdconfig, $ref=$["cause"]["raw"]
2020-07-07T03:17:15.139Z - [31merror[39m: Failed to lift app: message=Sails is taking too long to load.
```

Didn't look at your code but are you running the create_tables.js script?

**Comment by halkeye** [comment]
SF and I did a lot of debugging. I mean a lot. I have like 10 builds (okay looks like 6) up at https://hub.docker.com/r/halkeye/unraid-csmm/tags with different iterations.

From my testing, I'm pretty sure its due to the mysql logs being deleted after mysql has started up (also it means debugging is hard when it restrarts and deletes logs before you see any issues). Everything we tested lead us to the fact that the create tables script would time out, I can run it locally in like 6 seconds, so the 3000 seconds is overkill.

I personally would switch them to supervisord and have them rotate log files instead of forcing them to be deleted. That way if anything goes wrong on startup, it can still be fetched.

**Comment by ich777** [comment]
@halkeye You can delete the startup flag '--restart=unless-stopped' from the template then the container won't restart and the logs are still there.
But I think I will redisgn the container or at least change it so that the mysql files is also stored in the appdata directory.

**Comment by niekcandaele** [comment]
In any case, the core issue for the timeout is that the database tables are not being created properly. MySQL logs should help you debug

**Comment by ich777** [comment]
@niekcandaele I will look into that and also will redisign the container a little bit, I close that issue for now, thank you!

**Comment by ich777** [comment]
@halkeye I changed a few things under the hood can you try my image again or contact SF?

**Comment by SpectralForce** [comment]
> @halkeye I changed a few things under the hood can you try my image again or contact SF?

I will give this a try tonight after work.
